webkom/nyiabakus

components/Header/HeaderCards.tsx, components/Header/index.tsx, components/Header/styles.module.css, components/QuickLinks/index.tsx, components/QuickLinks/styles.module.css, pages/index.tsx, styles/globals.css
They are now sticky on desktop, try scrolling the page :o
=> Enhance quick-links

components/Card/index.tsx, components/Card/styles.module.css, components/Header/HeaderCards.tsx, components/Icon/index.tsx, components/InfoSectionPreparation/index.tsx, components/InfoSectionTrondheim/index.tsx, components/QuickLinks/styles.module.css
Add z-index to sticky links to stay above icons and LB-component.
=> Add icon to card component

components/FullscreenImage/index.tsx, components/FullscreenImage/styles.module.css, pages/events.tsx, styles/Home.module.css
=> Add zoomable images

components/Card/styles.module.css, components/FaqContent/index.tsx, components/FaqContent/styles.module.css, components/Header/HeaderCards.tsx, components/Header/index.tsx, components/Header/styles.module.css, components/InfoSectionFP/index.tsx, components/InfoSectionFP/styles.module.css, components/InfoSectionPreparation/index.tsx, components/InfoSectionStudentPub/index.tsx, components/InfoSectionStudentPub/styles.module.css, components/InfoSectionStudy/index.tsx, components/InfoSectionTrondheim/index.tsx, components/Navbar/index.tsx, components/QuickLinks/styles.module.css, pages/faq.tsx, styles/globals.css
- Update typos
- Update text from document
- Add text to header
- Add FAQ-page
- Add color to links
- Comment out TODO-mentions to make the page look more complete
Resolves ABA-447
Resolves ABA-481
=> Add FAQ-page and update texts

components/Button/index.tsx, components/Button/styles.module.css, components/Card/index.tsx, components/Card/styles.module.css, components/EventsListView/EventItem.tsx, components/EventsListView/styles.module.css, components/Header/HeaderCards.tsx, components/Header/styles.module.css, components/Icon/index.tsx, components/InfoSectionFP/index.tsx, components/InfoSectionPreparation/index.tsx, components/InfoSectionPreparation/styles.module.css, components/InfoSectionStudentPub/index.tsx, components/InfoSectionStudy/index.tsx, components/InfoSectionTrondheim/index.tsx, components/InfoSectionTrondheim/styles.module.css, components/QuickLinks/styles.module.css, pages/events.tsx
- Add cards to semester-start section
- Made cards grow to fit screen on smaller devices
- Add links to events on abakus.no (the same styling as on the cards - just on the right of the event-"card")
- Add links to card component to external sites/faq-site
=> Add button to card and event + responsive styling

components/InfoSectionStudentPub/index.tsx, components/Navbar/index.tsx, components/Navbar/styles.module.css, pages/events.tsx
=> Style navbar and hide images

components/Button/styles.module.css, components/Card/styles.module.css, components/EventsListView/styles.module.css, utils/api.ts
Ended up adding a margin where I didn't mean to earlier, so I fixed that.
Made the dayDescription text a little bit smaller, and update the selector (didn't work earlier, at least not on chrome).
=> Blacklist a new event and minor style changes

components/EventsListView/index.tsx, pages/events.tsx, schemas/dayDescription.ts
=> Make separate 5-year-boxes

components/EventsListView/index.tsx
Prime example of how to not force merge
=> Hotfix variable check

components/Navbar/styles.module.css
|Before|After|
|-|-|
|<img width="373" alt="Screenshot 2023-08-09 at 22 28 09" src="https://github.com/webkom/nyiabakus/assets/8343002/0facf04e-6a8f-4a07-bde7-09c71bb851a7">|<img width="373" alt="Screenshot 2023-08-09 at 22 27 42" src="https://github.com/webkom/nyiabakus/assets/8343002/8d6c5f83-5ad7-4054-a85c-c0b5036e129d">|
=> Improve navbar layout on mobile

components/EventsListView/index.tsx, components/EventsListView/styles.module.css
The gradient was blocking the interaction :P
Also made sure any specified link is opened in a new window so you don't have to re-navigate to the same part of the page:)
Resolves ABA-544
=> Make links in collapsibleitems clickable

components/InfoSectionStudy/index.tsx
Fixed a small typo found by @falbru
=> Fixed a small typo

components/Header/HeaderCards.tsx, components/InfoSectionFP/index.tsx, pages/fadderperioden.tsx, pages/masterfadderperioden.tsx, utils/constants.ts
Added the group as a constant to ensure that all places where it is referenced is updated when needed
=> Add facebook group for firstyears

utils/api.ts
Set isTBD to `false` and update dates for events
=> Update dates for events

components/InnbyttereContent/index.tsx, components/InnbyttereContent/styles.module.css, components/Navbar/index.tsx, components/Navbar/styles.module.css, pages/innbyttere.tsx
Et førsteutkast av en ny side med relevant info for innbyttere til Abakus<33 Her skal det komme litt mer info, men tenkte jobbe litt smidig og få ut litt nå i første omgang! 
**Endringer:** 
- Laget en ny side kalt "Innbyttere"
- Laget en komponent for innhold på denne siden
- Fylt inn en header, laget seksjon for infomøte og seksjon for "hvilken fadderperiode skal jeg delta på"
=> Abakus prosjekt innbyttere

utils/constants.ts
La til link til facebook gruppen til masterfadderperioden🔥
=> add facebook-link for mfp

components/InfoSectionFP/index.tsx, pages/masterfadderperioden.tsx
Added the meeting time for data and cybdat for mfp🗓️
=> update meeting time

CONTRIBUTING.md, README.md
Removed most of the yucky placeholder stuff from the README.md.
Added a CONTRIBUTING guide matching the one used for LEGO - but removed a few things to make it a little more legible.
=> Add contributing guide and clean readme

pages/om-abakus.tsx
By request from HS, a "Hvordan engasjere seg?" section has been added
=> Add how to engage section

pages/om-abakus.tsx
Updated names of HS members and Abakus HSP to those that are correct
ABA-1433
=> **request** fixoutdated info

.gitignore, components/EventsListView/index.tsx, next-env.d.ts, package.json, pages/_app.tsx, pages/_document.tsx, pages/studio/[[...index]].tsx, sanity.config.ts, yarn.lock
I guess this is nice, probably works idk.
=> Upgrade dependencies

components/FaqContent/index.tsx, pages/masterfadderperioden.tsx, utils/constants.ts
Added changes requested by Arrkom
=> update contactinfo, facebook groups, and when to meet

components/InfoSectionTaskForce/index.tsx, components/InfoSectionTaskForce/styles.module.css, studio/generated/sanity-schema.json, studio/generated/sanity.types.ts, studio/schemas/taskforce.ts
=> Add mail to taskforce
